version: '3.8'

services:
  web:
    command: bash -c "/app/.docker_compose_scripts/init_web_service.sh && tail -f log/development.log"
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      #- elasticsearch

  postgres:
    image: postgres:12
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  #elasticsearch:
  #  image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
  #  environment:
  #    - discovery.type=single-node
  #  ports:
  #    - "9200:9200"
