version: '3.8'

services:
  web:
    command: bash -c " tail -f log/development.log"
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      #- elasticsearch

  postgres:
    image: postgres:11
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6.2-alpine
    command: bash -c "redis-server --bind 0.0.0.0"
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  #elasticsearch:
  #  image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
  #  environment:
  #    - discovery.type=single-node
  #  ports:
  #    - "9200:9200"
