default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['DB_POOL'] || 5 %>
  username: <%= Rails.application.credentials.username_database %>
  password: <%= Rails.application.credentials.password_database %>
  host: localhost
  port: <%= Rails.application.credentials.port_database %>

production:
  <<: *default
  database: feedbin_production

development:
  <<: *default
  database: feedbin_development 

test:
  <<: *default
  database: feedbin_test