development:
  adapter: postgresql
  encoding: unicode
  database: feedbin_development
  pool: <%= ENV['DB_POOL'] || 5 %>
  username: <%= Rails.application.credentials.username_database %>
  password: <%= Rails.application.credentials.password_database %>
  host: postgres
  port: <%= Rails.application.credentials.port_database %>

test:
  adapter: postgresql
  encoding: unicode
  database: feedbin_test
  pool: <%= ENV['DB_POOL'] || 5 %>
  username: <%= Rails.application.credentials.username_database %>
  password: <%= Rails.application.credentials.password_database %>
  host: postgres
  port: <%= Rails.application.credentials.port_database %>

production:
  adapter: postgresql
  encoding: unicode
  database: feedbin_production
  pool: <%= ENV['DB_POOL'] || 5 %>
  username: <%= Rails.application.credentials.username_database %>
  password: <%= Rails.application.credentials.password_database %>
  host: postgres
  port: <%= Rails.application.credentials.port_database %>